is_enabled: true
log_level: info
weight: 200
endpoints:
  named_pipe: \\.\pipe\vscode_provider
  http: http://localhost:5030
  grpc: http://localhost:5031
jump_list_id: 1ced32d74a95c7bc
cache_ttl_minutes: 5