transport: NamedPipe
endpointNamedPipe: \\.\pipe\default_provider
endpointHttp: http://localhost:5000
endpointGrpc: http://localhost:5001
serialization: json
timeoutSeconds: 5
logLevel: Debug
settings:
  cache_ttl_minutes: 5
