is_enabled: true
log_level: info
endpoints:
  named_pipe: \\.\pipe\demo_provider
  http: http://localhost:5010
  grpc: http://localhost:5011
echo_prefix: Demo
action_path: notepad.exe
action_args: ''
