<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.66.0" />
    <PackageReference Include="protobuf-net" Version="3.2.30" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app_config.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\WindowsSearch.Common\WindowsSearch.Common.csproj" />
  </ItemGroup>

  <Target Name="StageSharedDependenciesAfterBuild" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <SharedDependenciesAfterBuild Include="$(TargetDir)*.dll" Exclude="$(TargetDir)Hub.dll" />
    </ItemGroup>

    <MakeDir Directories="$(TargetDir)bin\" Condition="'@(SharedDependenciesAfterBuild)' != ''" />
    <Copy SourceFiles="@(SharedDependenciesAfterBuild)" DestinationFolder="$(TargetDir)bin\" SkipUnchangedFiles="true" />
    <Delete Files="@(SharedDependenciesAfterBuild)" />
  </Target>

  <Target Name="StageSharedDependenciesAfterPublish" AfterTargets="Publish" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <SharedDependenciesAfterPublish Include="$(PublishDir)*.dll" Exclude="$(PublishDir)Hub.dll" />
    </ItemGroup>

    <MakeDir Directories="$(PublishDir)bin\" Condition="'@(SharedDependenciesAfterPublish)' != ''" />
    <Copy SourceFiles="@(SharedDependenciesAfterPublish)" DestinationFolder="$(PublishDir)bin\" SkipUnchangedFiles="true" />
    <Delete Files="@(SharedDependenciesAfterPublish)" />
  </Target>

</Project>
